/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ButtonNav: typeof import('./components/ButtonNav.vue')['default']
    CheckOutStepper: typeof import('./components/CheckOutStepper.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    PokemonCard: typeof import('./components/PokemonCard.vue')['default']
    PokemonDetailDialog: typeof import('./components/PokemonDetailDialog.vue')['default']
    PokemonJudgeRating: typeof import('./components/PokemonJudgeRating.vue')['default']
    PokemonList: typeof import('./components/PokemonList.vue')['default']
    PokeSelection: typeof import('./components/PokeSelection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VersionSelect: typeof import('./components/VersionSelect.vue')['default']
  }
}
